# Testing the code base against a specific Meilisearch feature
name: Beta tests

# Will only run for PRs and pushes to *-beta
on:
  push:
    branches: ['!bump-meilisearch-v*.*.*-beta', '**-beta']
  pull_request:
    branches: ['!bump-meilisearch-v*.*.*-beta', '**-beta']

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '18']
    name: integration-tests (Node.js ${{ matrix.node }})
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install:functions
      - name: Run tests with coverage
        run: yarn test:coverage
