name: publish to npm
on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Check release validity
        run: sh .github/scripts/check-release.sh
      - name: Check tag format
        run: sh .github/scripts/check-tag-format.sh "${{ github.event.release.prerelease }}"
      - name: Install dependencies
        run: yarn && yarn install:functions
      - name: Copy README in the functions directory
        run: cp README.md functions/
      - name: Publish with latest tag
        if: "!github.event.release.prerelease && !contains(github.ref, 'beta')"
        run: |
          cd functions
          npm publish .
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish with beta tag
        if: "github.event.release.prerelease && contains(github.ref, 'beta')"
        run: |
          cd functions
          npm publish . --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
